# Generated by Django 4.2 on 2023-06-23 09:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_date_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
