# Generated by Django 4.2 on 2023-06-29 18:47

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
